import { GraduationCap, Users, Info } from 'lucide-react';
import { routes } from '../../data/routes';
import type { TravelRoute } from '../../data/routes';
import { pricing } from '../../config/pricing';
import { calculatePrice, money } from '../../lib/pricing';
export type Party = { total:number;students:number;discount:boolean };
export default function Calculator({route,onSelect,party,onChange,onRequest}:{route:TravelRoute;onSelect:(route:TravelRoute)=>void;party:Party;onChange:(party:Party)=>void;onRequest:()=>void}){
 const price=calculatePrice(route.demoBasePrice,party.total,party.students,party.discount);
 function totalChange(v:number){const total=Math.min(50,Math.max(1,Math.trunc(v)||1));onChange({...party,total,students:Math.min(total,party.students)})}
 return <section className="calculator section" id="calculator"><div className="calculator-copy"><span className="eyebrow">ПУТЕШЕСТВИЕ ПО КАРМАНУ</span><h2>Сколько стоит<br/><em>твоё путешествие?</em></h2><p>Собери свою компанию.<br/>Посчитаем стоимость и студенческую экономию.</p><div className="calculator-note"><Info size={20}/><span>{pricing.enabled?pricing.disclaimer:'Цены уточняются при согласовании программы'}<small>Условия тура и отдельные музейные билеты согласуются дополнительно.</small></span></div></div><div className="calculator-card"><div className="calculator-fields"><label>Город отправления<select value={route.id} onChange={e=>onSelect(routes.find(r=>r.id===e.target.value)!)}>{routes.map(r=><option value={r.id} key={r.id}>{r.origin}</option>)}</select></label><div className="field-pair"><label>Путешественники<input type="number" min="1" max="50" value={party.total} onChange={e=>totalChange(Number(e.target.value))}/></label><label>Из них студенты<input type="number" min="0" max={party.total} value={party.students} onChange={e=>onChange({...party,students:Math.min(party.total,Math.max(0,Math.trunc(Number(e.target.value))||0))})}/></label></div><label className="switch-label"><span><GraduationCap size={21}/>Я студент<small>Применить скидку {pricing.studentDiscount*100}%</small></span><input type="checkbox" role="switch" checked={party.discount} onChange={e=>onChange({...party,discount:e.target.checked,students:e.target.checked&&party.students===0?1:party.students})}/></label></div><div className="price-summary" aria-live="polite">{pricing.enabled?<><div className="price-row"><span>Базовая стоимость × {price.count}</span><b>{money(price.base)} BYN</b></div><div className="price-row"><span>Скидка {party.discount?pricing.studentDiscount*100:0}% · студентов: {price.students}</span><b>−{money(price.saving)} BYN</b></div><div className="total-row"><span>Итого за компанию</span><strong data-testid="price-total">{money(price.total)} <small>BYN</small></strong></div><div className="savings"><GraduationCap size={18}/><span>Ваша экономия: <b data-testid="price-savings">{money(price.saving)} BYN</b></span></div><small className="demo-label">{pricing.label} · {pricing.disclaimer}</small></>:<p>Стоимость уточняется при согласовании программы.</p>}</div><button className="button" onClick={onRequest}><Users size={18}/>Сформировать заявку</button></div></section>;
}
