import { useState } from 'react';
import { GraduationCap, Info } from 'lucide-react';
import { routes } from '../../data/routes';
import type { TravelRoute } from '../../data/routes';
import { pricing } from '../../config/pricing';
import { calculatePrice, money } from '../../lib/pricing';
export type Party = { total:number;students:number };
export default function Calculator({route,onSelect,party,onChange,onRequest}:{route:TravelRoute;onSelect:(route:TravelRoute)=>void;party:Party;onChange:(party:Party)=>void;onRequest:()=>void}){
 const [capped,setCapped]=useState(false);
 const price=calculatePrice(route.demoBasePrice,party.total,party.students);
 const pct=pricing.studentDiscountPercent;
 // Students can never outnumber travelers: the count is capped and the visitor is told why.
 function totalChange(v:number){const total=Math.min(pricing.maxTravelers,Math.max(1,Math.trunc(v)||1));setCapped(party.students>total);onChange({total,students:Math.min(total,party.students)})}
 function studentsChange(v:number){const students=Math.max(0,Math.trunc(v)||0);setCapped(students>party.total);onChange({...party,students:Math.min(party.total,students)})}
 return <section className="calculator section" id="calculator"><div className="calculator-copy"><h2>Price calculator</h2><p>Choose a departure city and the size of your group. Students get {pct}% off automatically.</p><div className="calculator-note"><Info size={20}/><span>How the total is calculated<small>Regular travelers × starting price + students × starting price × {(100-pct)/100}</small></span></div></div><div className="calculator-card"><div className="calculator-fields"><label>Departure city<select value={route.id} onChange={e=>onSelect(routes.find(r=>r.id===e.target.value)!)}>{routes.map(r=><option value={r.id} key={r.id}>{r.origin}</option>)}</select></label><div className="field-pair"><label>Travelers<input type="number" min="1" max={pricing.maxTravelers} value={party.total} onChange={e=>totalChange(Number(e.target.value))}/></label><label>Students among them<input type="number" min="0" max={party.total} value={party.students} onChange={e=>studentsChange(Number(e.target.value))}/></label></div>{capped&&<p className="field-hint" role="status">There can’t be more students than travelers, so the number of students is set to {party.students}.</p>}</div><div className="price-summary" aria-live="polite">{pricing.enabled?<><div className="price-row"><span>Regular tickets<small>{price.regular} × {money(price.basePrice)} {pricing.currency}</small></span><b data-testid="price-regular">{money(price.regularCost)} {pricing.currency}</b></div><div className="price-row student"><span>Student tickets, −{pct}%<small>{price.students} × {money(price.studentPrice)} {pricing.currency}</small></span><b data-testid="price-students">{money(price.studentCost)} {pricing.currency}</b></div><div className="total-row"><span>Total for the group</span><strong data-testid="price-total">{money(price.total)} <small>{pricing.currency}</small></strong></div><div className="savings"><GraduationCap size={18}/><span>Group savings: <b data-testid="price-savings">{money(price.saving)} {pricing.currency}</b></span></div><small className="demo-label">{pricing.note}</small></>:<p>The price is confirmed when the program is agreed.</p>}</div><button className="button" onClick={onRequest}>Create a request</button></div></section>;
}
