import { GraduationCap, Info } from 'lucide-react';
import { routes } from '../../data/routes';
import type { TravelRoute } from '../../data/routes';
import { pricing } from '../../config/pricing';
import { calculatePrice, money } from '../../lib/pricing';
export type Party = { total:number;students:number;discount:boolean };
export default function Calculator({route,onSelect,party,onChange,onRequest}:{route:TravelRoute;onSelect:(route:TravelRoute)=>void;party:Party;onChange:(party:Party)=>void;onRequest:()=>void}){
 const price=calculatePrice(route.demoBasePrice,party.total,party.students,party.discount);
 function totalChange(v:number){const total=Math.min(50,Math.max(1,Math.trunc(v)||1));onChange({...party,total,students:Math.min(total,party.students)})}
 return <section className="calculator section" id="calculator"><div className="calculator-copy"><h2>Price calculator</h2><p>Choose a route, enter the size of your group and see the total with the student discount.</p><div className="calculator-note"><Info size={20}/><span>{pricing.enabled?pricing.disclaimer:'Prices are confirmed when the program is agreed'}<small>Tour terms and individual museum tickets are arranged separately.</small></span></div></div><div className="calculator-card"><div className="calculator-fields"><label>Departure city<select value={route.id} onChange={e=>onSelect(routes.find(r=>r.id===e.target.value)!)}>{routes.map(r=><option value={r.id} key={r.id}>{r.origin}</option>)}</select></label><div className="field-pair"><label>Travelers<input type="number" min="1" max="50" value={party.total} onChange={e=>totalChange(Number(e.target.value))}/></label><label>Students among them<input type="number" min="0" max={party.total} value={party.students} onChange={e=>onChange({...party,students:Math.min(party.total,Math.max(0,Math.trunc(Number(e.target.value))||0))})}/></label></div><label className="switch-label"><span><GraduationCap size={21}/>I’m a student<small>Apply the {pricing.studentDiscount*100}% discount</small></span><input type="checkbox" role="switch" checked={party.discount} onChange={e=>onChange({...party,discount:e.target.checked,students:e.target.checked&&party.students===0?1:party.students})}/></label></div><div className="price-summary" aria-live="polite">{pricing.enabled?<><div className="price-row"><span>Base price × {price.count}</span><b>{money(price.base)} BYN</b></div><div className="price-row"><span>Discount {party.discount?pricing.studentDiscount*100:0}% · students: {price.students}</span><b>−{money(price.saving)} BYN</b></div><div className="total-row"><span>Total for the group</span><strong data-testid="price-total">{money(price.total)} <small>BYN</small></strong></div><div className="savings"><GraduationCap size={18}/><span>You save: <b data-testid="price-savings">{money(price.saving)} BYN</b></span></div><small className="demo-label">{pricing.label} · {pricing.disclaimer}</small></>:<p>The price is confirmed when the program is agreed.</p>}</div><button className="button" onClick={onRequest}>Create a request</button></div></section>;
}
