import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const out='../../work/qa';fs.mkdirSync(out,{recursive:true});
const browser=await chromium.launch({headless:true});
const context=await browser.newContext({viewport:{width:1920,height:1080},permissions:['clipboard-read','clipboard-write'],reducedMotion:'reduce'});
const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:5173/',{waitUntil:'networkidle'});
await page.screenshot({path:`${out}/desktop-home.png`});
await page.locator('#map').scrollIntoViewIfNeeded();await page.waitForTimeout(1000);await page.screenshot({path:`${out}/desktop-map.png`});
for(const city of ['Минск','Гродно','Брест','Могилёв','Гомель','Витебск']){
 await page.getByRole('group',{name:'Выбор города отправления'}).getByRole('button',{name:city,exact:true}).click();
 assert.equal(await page.locator('.city-tabs button[aria-pressed=true]').innerText(),city);
 await page.locator('.panel-stops button').first().click();
 await page.waitForTimeout(950);assert.ok(await page.locator('.leaflet-popup').isVisible());
 assert.ok(await page.locator('.popup-photo').evaluate(el=>el.complete&&el.naturalWidth>0));
 await page.getByRole('button',{name:'Вернуться к маршруту'}).click();
}
await page.getByRole('group',{name:'Выбор города отправления'}).getByRole('button',{name:'Минск',exact:true}).click();
await page.locator('#calculator').getByLabel('Путешественники',{exact:true}).fill('4');
await page.locator('#calculator').getByLabel('Из них студенты').fill('2');
await page.locator('#calculator').getByRole('switch').check();
assert.equal(await page.getByTestId('price-total').innerText(),'248,4 BYN');
assert.equal(await page.getByTestId('price-savings').innerText(),'27,6 BYN');
await page.locator('#calculator').getByLabel('Путешественники',{exact:true}).fill('1');
assert.equal(await page.locator('#calculator').getByLabel('Из них студенты').inputValue(),'1');
await page.locator('#calculator').getByRole('button',{name:'Сформировать заявку'}).click();
await page.getByRole('dialog').getByLabel('Имя путешественника').fill('Анна');
await page.getByRole('dialog').getByLabel('Контакт',{exact:true}).fill('anna@example.com');
await page.getByRole('dialog').getByLabel('Предпочтительная дата').fill('2027-06-15');
await page.getByRole('dialog').getByRole('button',{name:'Показать предпросмотр'}).click();
assert.ok(await page.getByRole('dialog').getByText('Заявка не отправлена, бронирование не подтверждено.',{exact:true}).isVisible());
await page.getByRole('button',{name:'Скопировать заявку'}).click();await page.getByRole('button',{name:'Скопировано',exact:true}).waitFor({state:'visible'});assert.ok(await page.getByRole('button',{name:'Скопировано',exact:true}).isVisible());
await page.screenshot({path:`${out}/application.png`});await page.getByRole('button',{name:'Закрыть заявку'}).click();
await page.getByRole('button',{name:'Режим презентации',exact:true}).click();await page.locator('body').click({position:{x:5,y:5}});await page.keyboard.press('ArrowRight');
assert.equal(await page.locator('.city-tabs button[aria-pressed=true]').innerText(),'Гродно');
await page.locator('.panel-stops button').first().click();await page.waitForTimeout(950);await page.screenshot({path:`${out}/presentation.png`});
await page.getByRole('button',{name:'Выйти из презентации'}).click();
await page.goto('http://127.0.0.1:5173/?route=minsk#program',{waitUntil:'networkidle'});
await page.locator('.timeline-image').first().click();await page.getByRole('button',{name:'Следующее фото'}).click();assert.ok(await page.locator('.gallery-controls').getByText('2 / 3').isVisible());await page.getByRole('button',{name:'Закрыть фотографии'}).click();
await page.goto('http://127.0.0.1:5173/?route=brest#map',{waitUntil:'networkidle'});assert.equal(await page.locator('.city-tabs button[aria-pressed=true]').innerText(),'Брест');
const broken=await page.locator('img').evaluateAll(imgs=>imgs.filter(img=>img.complete&&img.naturalWidth===0).map(img=>img.src));assert.deepEqual(broken,[]);
await page.setViewportSize({width:390,height:844});await page.goto('http://127.0.0.1:5173/',{waitUntil:'networkidle'});await page.screenshot({path:`${out}/mobile-home.png`});
assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await page.getByRole('button',{name:'Меню',exact:true}).click();await page.locator('header nav').getByRole('link',{name:'Карта путешествий'}).click();await page.waitForTimeout(500);assert.equal(await page.getByRole('button',{name:'Меню',exact:true}).getAttribute('aria-expanded'),'false');
await page.locator('.map-layout').scrollIntoViewIfNeeded();await page.screenshot({path:`${out}/mobile-map.png`});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
assert.deepEqual(errors,[]);console.log('PASS: six routes, markers/photos, calculator, application/copy, presentation/keyboard, gallery, deep link, mobile menu/layout, no runtime errors.');
await browser.close();
